name: Publish to Modrinth

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Download Release Asset
        id: download_asset
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download ${{ github.event.release.tag_name }} --pattern "*.jar" --dir .
          JAR_PATH=$(ls *.jar | grep -v "sources" | head -n 1)
          echo "path=${JAR_PATH}" >> $GITHUB_OUTPUT

      - name: Modrinth Publish
        uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MODRINTH_PAT }}
          project-id: "ktM6wXUv"
          version: ${{ github.event.release.tag_name }}
          files: ${{ steps.download_asset.outputs.path }}
          loaders: |
            fabric
          game-versions: |
            26.2
            26.1.2